### ISSUE TITLE
Exceptions sections of XML docs are not being shown in descrription summaries

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp-core-api-docs#10]
e.g. `List.average` the XML docs contains this:

https://github.com/dotnet/fsharp/blob/e690e922d3ed6991e26e712fea76129bec0eb399/src/fsharp/FSharp.Core/list.fsi#L34

However the output display doesn't contain this information.

This will likely be an FSharp.Formatting bug.

**Comment by baronfel** [comment]
Yes, this is part of the RawData (in the 'exception' section), but not rendered by FSF in the `FullText` member or the `<default>` Section.

**Comment by Krzysztof-Cieslak** [comment]
I've patched RawData while ago to support any kind of tag in XMLDoc (I was planning to use it for DocTest tool), as far as I remember only limited set of typical tags was supported by default by `FullText`

**Comment by dsyme** [comment]
Cool if you can point me to any of these patches over FSharp.Formatting I can get them integrated in (or somehow done)

**Comment by Krzysztof-Cieslak** [comment]
Oh, I mean, those changes are in F#.Formatting - that's why `RawData` member returns all content correctly.

As for why exceptions are not working with `FullText` - it seems there is a typo here - https://github.com/fsprojects/FSharp.Formatting/blob/2a1d1204b88f74095df5e057d294ab0368f8007a/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L911 ;-)

**Comment by Krzysztof-Cieslak** [comment]
Fix - https://github.com/fsprojects/FSharp.Formatting/pull/542

**Comment by dsyme** [comment]
lol

**Comment by cartermp** [comment]
Is this what you saw @dsyme ?

<img width="403" alt="image" src="https://user-images.githubusercontent.com/6309070/87951290-3c42c700-ca5d-11ea-9027-5d8049e868c9.png">

**Comment by Krzysztof-Cieslak** [comment]
As far as I understand F#.Formatting is able to resolve only exceptions (and crefs in general) only from dlls processed in the current context. It seems it may be fairly difficult to work around - we would potentially need to make F#.Formatting also process dependencies of our dlls.

Ofc, we should remove this huge `UNRESOLVED` string.  https://github.com/fsprojects/FSharp.Formatting/blob/2a1d1204b88f74095df5e057d294ab0368f8007a/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L920-L925

**Comment by baronfel** [comment]
opened https://github.com/fsprojects/FSharp.Formatting/issues/545 up to track this, btw.

**Comment by baronfel** [comment]
I see what you mean about the exceptions from dependencies, it's just one surfacing of the more general 'where does this type live' question for third-party types. It might be possible to have a shim for BCL types at the very least (making links to docs.ms.com), leaving open the very wide question of where to find docs for OSS types.

**Comment by baronfel** [comment]
Closing this as the exceptions are now shown, discussion about rendering/etc can go in a new issue.
