### ISSUE TITLE
Move to fsharp/fsharp-core-api-docs

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp-core-api-docs#16]
@baronfel @cartermp 

After thinking it over let's just move this to fsharp/fsharp-core-api-docs

The group we had together on the call last night act as a sufficient engineering quorum to go ahead with this. I think we can all see we eventually want searchable docs (possibly of other projects too) on fsharp.org. 

I will move it now and fork back here so incoming aka.ms links links don't immediately break, then we can adjust

**Comment by baronfel** [comment]
Closing because the move has been done.
