### ISSUE TITLE
URL to Result module broken

### ISSUE THREAD

**Issue by bender2k14** [fsharp/fsharp-core-api-docs#25]
If I search for `Result` and select the first hit for the `Result` module...

![2020-07-29_15-26-56_210_chrome](https://user-images.githubusercontent.com/34664007/88849864-1f6e6800-d1b0-11ea-9e38-bf74900e7dde.png)

...then I am taken to https://fsharp.github.io/reference/FSharp.Core/fsharp-core-resultmodule.html which is a broken link

![2020-07-29_15-27-14_211_chrome](https://user-images.githubusercontent.com/34664007/88849970-4462db00-d1b0-11ea-87c9-b64cf8b0c908.png)

**Comment by bender2k14** [comment]
Now it goes to...
```
https://fsharp.github.io/fsharp-core-api-docs//reference/FSharp.Core/fsharp-core-resultmodule.html
```

...instead of the expected result of...
```
https://fsharp.github.io/fsharp-core-api-docs/reference/FSharp.Core/fsharp-core-resultmodule.html
```

...(the difference being `//` vs `/`) but it still works.

**Comment by baronfel** [comment]
the double slashes _are_ slightly annoying, but I'm about to do a refactor/rewrite of this repo anyway to see how the new consolidated templates in FSharp.Formatting look, so I was ok with a little messiness here :)

**Comment by dsyme** [comment]
@baronfel Am doing similar (mostly to flush out bugs in the HTML generation) - can we chat?

**Comment by dsyme** [comment]
@baronfel My strategy is just to rip out everything and fix the default 'fsdocs' experience against an FSharp.Core from the nuget package, see https://github.com/fsharp/fsharp-core-api-docs/compare/master...dsyme:fd for work in progress.  Note -5000, +13. My theory is that if we can make the default experience excellent for FSharp.Core then we'll be in good shape across the ecosystem.

Notes

- Some fixes to fsdocs are needed.  I'll aim to get a new tool published today

- I'd like to keep making small design improvements in the CSS and HTML, as well as some generation changes (e.g. possibly to optionally generate a page for each method/property too, which FSHarp.Core really deserves though is a bit OTT for some other libraries with sparse comments)

**Comment by baronfel** [comment]
@dsyme oh if you're actively working on converting this repo to F#F that's great, don't mean to step on any toes yet.  Sounds like I can take your branch for a trial run and see how it all looks.

One thing I am interested in is how the F#F doc generation will handle path-prefixes, like I had to fix in this repo recently.
