### ISSUE TITLE
Search index doesn't include `List.xyz` etc eg List.allPairs

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp-core-api-docs#7]
Title says it all

This was found in the F# community dugnad cleanup session today

**Comment by baronfel** [comment]
There are a few ways to handle this:

* we can change the generation of the index to include multiple variations of members (ie 'allPairs' and 'List.allPairs') when a member is in a `RequireQualifiedAccess` context. This would be in `generators/lunr.fsx`
* we can tweak the lunr search API query directly to try to be more lenient with the existing fuzzy searches and ordering of results. This would be in `static/js/search.js`.

**Comment by dsyme** [comment]
> we can change the generation of the index to include multiple variations of members (ie 'allPairs' and 'List.allPairs') 

I fixed this in FSharp.Formatting core API docs generator - we can now either switch to using the whole docs generator (`ApiDocs.GenerateHtml` or `dotnet fsdocs build`) or use `ApiDocs.GenerateSearchIndexFromModel`.

Also the `Microsoft.` stripping is now actually done in model preparation for all DLLs in all doc generation, see https://github.com/fsprojects/FSharp.Formatting/blob/2a1d1204b88f74095df5e057d294ab0368f8007a/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L1145.
