### ISSUE TITLE
In remarks sections XML containing <c>xyz</c> are not being shown correctly

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp-core-api-docs#9]
e.g. List.average XML contains this:

        /// <remarks>Raises <c>System.ArgumentException</c> if <c>list</c> is empty.</remarks>

But the `<c></c>` block is not being shown

**Comment by baronfel** [comment]
We'll need to update to latest F# Formatting to be sure, but that entire section is taken verbatim from the `DocComment.FullText` on each member.

**Comment by baronfel** [comment]
Yes, the FullText and the Sections on DocComment both strip that information.

Strangely, the RawData looks fine, but would require some post-processing to patch up some links. For example, average returns the following RawData dict:

```
summary => Returns the average of the elements generated by applying the function to each element of the list.
param-projection => The function to transform the list elements into the type to be averaged.
param-list => The input list.
returns => The resulting average.
remarks => Raises System.ArgumentException if list is empty.
c-0 => System.ArgumentException
c-1 => list
exception => Thrown when the list is empty.
```

this has echoes of other issues raised in F# Formatting about how it doesn't parse the doc comments into usable sections. (Here all of the rendered data is put into a <default> section).

**Comment by baronfel** [comment]
After the update to F#F 6 this remains the same, so this'll need to be fixed at that level.

**Comment by Krzysztof-Cieslak** [comment]
This function needs to add case for `<c></c>` - https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L841-L876

**Comment by Krzysztof-Cieslak** [comment]
Fix - https://github.com/fsprojects/FSharp.Formatting/pull/543
